---
title: "Celeste Pilegard's CV"
author: Celeste Pilegard
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---
``` {r, echo=FALSE}
# Get rid off the sidebar from the second page
# (source:https://www.anabellelaurent.com/slides/rladies_pagedown/cvwithpagedown#18
# .pagedjs_page:not(:first-of-type) {
#  --sidebar-width: 0rem;
#  --sidebar-background-color: #ffffff;
#  --main-width: calc(var(--content-width) - var(--sidebar-width));
#  --decorator-horizontal-margin: 0.2in;
# }
```

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1X7ymi0SAdIM-GbTtLmE6wr81_n6inYj_Vieaowv4RPY",  
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================


```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
# datadrivencv::build_network_logo(CV$entries_data)
```


```{r}
# if(params$pdf_mode){
#   cat("View this CV online with links at ")
# } else {
#   cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://)")
# }
```

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```

Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Last updated `r Sys.Date()`

Made with [pagedown](https://github.com/rstudio/pagedown)

[github.com/pilegard/cv](https://github.com/pilegard/cv)


Main
================================================================================

Celeste Pilegard {#title}
--------------------------------------------------------------------------------

&nbsp;Curriculum Vitae


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```

Professional Appointments {data-icon=institution data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('prof_experience')
```

Publications {data-icon=book}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('pubs')
```

Awards and Fellowships {data-icon=award}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('awards')
```

Grant Support {data-icon=project-diagram}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('grants')
```

Conference Activity {data-icon=users}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('conferences')
```

Teaching {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('teaching')
```

Mentorship {data-icon=user-graduate}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('mentor')
```

Invited Talks, Teaching Talks, and Workshops {data-icon=comment-alt}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('talks')
```

Professional Service {data-icon=cogs}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('professional_service')
```


Department and University Service {data-icon=cogs}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('uni_service')
```


Outreach {data-icon=globe}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('outreach')
```

Other Professional Experience {data-icon=briefcase}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('other_pro')
```

<!--
Professional Development {data-icon=chart-line}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('profdev')
```
-->


```{r}
CV %<>% print_links()
```
